### ISSUE TITLE
Error after logging in

### ISSUE THREAD

**Issue by jfmcbrayer** [enkiv2/fern#1]
I verified that this happens using Python 2.7 on Fedora linux. It fetches the timeline, displays the UI (with blank cards for toots), then displays the short error "Something happened: addstr() returned ERR". After typing any key, the following traceback:

```Traceback (most recent call last):
  File "./fern", line 716, in main
    mainloop()
  File "./fern", line 671, in mainloop
    drawPanelContents(tl[tlIdx:], hlIdx)
  File "./fern", line 321, in drawPanelContents
    drawPanels(fillInDomain(mastodon.account_verify_credentials()["acct"]), ROWS, COLS, selectedIdx)
  File "./fern", line 271, in drawPanels
    scr.addstr(centerPad("[(b)oost] [(f)av] [mark_(u)nread] "+clopen+" [(t)hread_view] [(F)etch_new] [(:)_command]", cols).replace("_", " "), curses.color_pair(menunum))
error: addstr() returned ERR
Traceback (most recent call last):
  File "./fern", line 724, in <module>
    main()
  File "./fern", line 708, in main
    main()
  File "./fern", line 721, in main
    raise e
error: addstr() returned ERR
```

**Comment by enkiv2** [comment]
Is this using an already-existing set of credentials created while running it in python 3?

**Comment by jfmcbrayer** [comment]
No, it happens with a freshly deleted ~/.fern directory

**Comment by enkiv2** [comment]
Ok, I'll see if I can replicate it.

**Comment by gustafe** [comment]
I get this error too, but with slightly different line numbers.

I tried using fern in an 80x24 window, and it failed on startup. After trying on a larger window, I was able to set up my credentials, but I get this error on both the large screen and the small. This leads me to suspect that the window size has some limits that aren't being respected when the window is the "wrong size".

![image](https://user-images.githubusercontent.com/8576740/59424496-621a8880-8dd4-11e9-8427-39f535aa4578.png)

My stacktrace:

```
$fern
Traceback (most recent call last):
  File "/usr/bin/fern", line 718, in main
    mainloop()
  File "/usr/bin/fern", line 673, in mainloop
    drawPanelContents(tl[tlIdx:], hlIdx)
  File "/usr/bin/fern", line 323, in drawPanelContents
    drawPanels(fillInDomain(mastodon.account_verify_credentials()["acct"]), ROWS, COLS, selectedIdx)
  File "/usr/bin/fern", line 274, in drawPanels
    drawLogo(leftPanelCols+(int(COLS-leftPanelCols)/2), int(ROWS/2))
  File "/usr/bin/fern", line 165, in drawLogo
    scr.addstr(int(i+yoffset), int(xoffset), line, curses.color_pair(menunum))
error: addstr() returned ERR
Traceback (most recent call last):
  File "/usr/bin/fern", line 726, in <module>
    main()
  File "/usr/bin/fern", line 723, in main
    raise e
error: addstr() returned ERR
```

**Comment by enkiv2** [comment]
Hmm... So, fern resizes the elements based on the window size, & a window
that's too small might cause the size for one of the elements to be zero or
it might cause offsets to be negative. I'll try to figure out what the
limits on window size are & whether or not they can be made better (ex., by
dropping the logo on small windows or dropping other display elements).

GCUPC, are you also using a small window? I'm leaning toward the idea that
I broke window-drawing on newly-created credentials at some point and
didn't notice, & that to get around it you've gotta restart the application
after registering it (i.e., with fillInDomain() returning null or
something).

**Comment by enkiv2** [comment]
Alright, I've fixed the handful of cases where a larger terminal size is assumed. I've tested on 80x24 but it will still fail on some smaller terminal sizes.

359e71bd267c48125e638e6b23fd247ddf9a2303
