### ISSUE TITLE
Add image support?

### ISSUE THREAD

**Issue by shellkr** [enkiv2/fern#4]
Have you thought about adding image support with the help of for example w3mimgdisplay?

**Comment by enkiv2** [comment]
I don't plan to add image support in mainline fern. It'd add dependencies & complications.

That said, I might add support for configurable pagers (in order to deal with situations like posts from instances with long upper limits inside small terminals -- the message window does not scroll & I'm not planning to add scroll support to it), & if I do that, setting pager to w3m with image support turned on will let you view images.

**Comment by enkiv2** [comment]
THAT SAID -- if you want to submit a pull request, & can make the diff small & behavior degrade gracefully in the case that the dependency is missing (i.e., inserting a couple lines into message rendering & a couple lines up top for an import, where normal behavior remains if w3mimgdisplay python bindings aren't already installed) I'll merge it.

My policy is basically that fern code should remain a single file, no more than 1000 lines, & depend on nothing but Mastodon.py, no matter what features are added.

**Comment by shellkr** [comment]
I was expecting you wouldn't like it but thought I at least could ask. Your suggested solution would be great. A SNS like Mastodon do use a lot of media so having a way to view it would be a great addition.

Fri Jun 14 15:15:32 GMT+02:00 2019 John Ohno <notifications@github.com>:

**Comment by enkiv2** [comment]
As of 5c0110d8d06a97cb723334ac175ff62b971ae910, if you set your `BROWSER` environment variable to `w3m -o auto_image=TRUE`, pressing `g` will open the currently selected message in w3m with images loaded.

It also respects the value of `$PAGER` if `$BROWSER` isn't set, and falls back to `$VISUAL`, then `$EDITOR`, then `less`.

If `$BROWSER` is set, it sends HTML, otherwise it sends plain text to the pager.

**Comment by shellkr** [comment]
I just tried this and it almost worked as it should. The issue is that it does not open `w3m $url` but instead parses and sends the content of a post. Which means you will just get a long line of text in w3m and no images.

I hacked a bit but was little difficult when I am not familiar with the variables... but something like this works. From line 453.
```
               if browser!="":
                        subprocessRun(browser+" "+tl[tlIdx]["url"])

```
This will not open the post but the whole thread. Didn't figure out how to open just the post.

**Comment by enkiv2** [comment]
Hmm...

W3m ought to be able to recognize the input as html. Sending the url will
probably mean that private posts (ex. DMs) can't be displayed. I'll take
another look.

To be clear, you set BROWSER=w3m and not PAGER=w3m, right?

**Comment by shellkr** [comment]
Yes, BROWSER=w3m as you instructed. I will take another look later. Maybe w3m goes into pager mode somehow. Need to go to work now though.

**Comment by enkiv2** [comment]
It looks like w3m sometimes can't identify the input as HTML, so you'll have to add `-T text/html` to BROWSER. 

My copy of w3m doesn't seem to be built with image support, so I can't verify that images are showing.

**Comment by shellkr** [comment]
Yeah, that makes it render but still does not show the images. I don't know if it is just me but I can not see a url to the image, just the "content" part. I can see the image url in fern but not after in w3m. Perhaps the url to the image is not sent to w3m?

**Comment by enkiv2** [comment]
I think w3m is ignoring the hint to render images. The URL is indeed sent
(as you can see by setting BROWSER=less and reading the HTML -- it's even a
fully-qualified URL). I don't use w3m's image support often enough to be
able to debug it (and back when I used it, I found it often sort of
randomly dropped images or put them in the wrong place anyway), but I think
this now comes down to making w3m display the image elements properly (by
hinting on the command line or something) -- not the sort of thing that
fern code should be doing.

**Comment by shellkr** [comment]
Well, actually.. this is what BROWSER=less gives me on this. No image url is forwarded.

![scrot_20190625-214905_662x118](https://user-images.githubusercontent.com/837668/60128651-6a3ed480-9793-11e9-8e70-49bf67d09485.png)

less output:
```less 
<html><body><p><a href="https://mstdn.io/tags/boris" class="mention hashtag" rel="tag">#<span>Boris</span></a> <a href="https://mstdn.io/tags/bus" class="mention hashtag" rel="tag">#<span>bus</span></a></p></body></html>
```

![scrot_20190625-215335_621x130](https://user-images.githubusercontent.com/837668/60128844-e6391c80-9793-11e9-8f9f-223fb8ba47bd.png)

less output:
```less 
<html><body><p><span class="h-card"><a href="https://playvicious.social/@paeneultima" class="u-url mention" rel="nofollow noopener" target="_blank">@<span>paeneultima</span></a></span> This is what upset them</p></body></html>
```

**Comment by enkiv2** [comment]
That is very strange. The original post had an image in it? I certainly
didn't strip it...

**Comment by shellkr** [comment]
Yes, as you can see in the image it had image url's that didn't get through to less. Only the text part got through. I have investigated a bit and according to https://mastodonpy.readthedocs.io/en/stable/ you have 'content' but also a 'media_attachments' for media attached in the toot.

**Comment by enkiv2** [comment]
You're right -- I don't process media_attachments, so anything that has a
media attachment that isn't present in the toot content is not visible in
the pager. (I can't remember if I even process that for text-only toot
display!) I'll take a look at processing that today, & see whether or not
doing so can be made straightforward (since media attachments theoretically
can be of an arbitrary media type, not just images.)

**Comment by enkiv2** [comment]
Alright, in cases where media attachments exist but are not linked to in the content, the pager now gets generated HTML for embedding them as of commit cb551388d5f136e19be7701882645243ed09eab7

This will double up any embeds that are actually linked in the content.

**Comment by shellkr** [comment]
That did it! Now it works as it should... and btw... I packaged it up and put it out on the AUR.

**Comment by ZekDtonik** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
sudaoyi, @jyjsjd, @xream, @HDark15, @zhipengit, @OfficialDarkComet, @WayneGongCN, @houyi1205, @liy05, @CarlisleChan, @LI3GE, @kaliwdsn, @bitsmuggler, @iMyth, @LethiciaFelix, @zhaiyh07, @PoplarDddCN, @rsheftel, @dllhlx, @DeweyLiu, @A-khateeb, @zaryanezrya, @lbb00, @henryhardy, @jrmain, @copyrighthero, @hamdichau, @lichangwei, @mo2feng, @paul-nechifor, @matchai, @imsaux, @alexandrehrk, @a30929959, @DominikHerold, @yukselberkay, @Leannhtx, @STASiAN, @gzgithub, @binhbo12456, @adamhos, @zhukangfeng, @mvpvg, @LightCandle, @saji89, @cfgxy, @dejwrocks, @Leptinox, @zrj1884, @mmanolakeris
